language: java
jdk:
  - oraclejdk8

script:
  - mvn test jacoco:report coveralls:report

cache:
  directories:
    - '$HOME/.m2/repository'
#after_success:
#  - mvn clean test jacoco:report coveralls:report